# Generated by Django 4.2.8 on 2023-12-07 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientAPI', '0006_order_goods_alter_order_datetimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetimes',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 20, 23, 39, 769146, tzinfo=datetime.timezone.utc), verbose_name='datetimes'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='goods',
        ),
        migrations.AddField(
            model_name='order',
            name='goods',
            field=models.ManyToManyField(to='ClientAPI.goods'),
        ),
    ]
