# Generated by Django 4.2.8 on 2023-12-07 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientAPI', '0009_alter_goods_description_alter_order_datetimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetimes',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 21, 16, 54, 313410, tzinfo=datetime.timezone.utc), verbose_name='datetimes'),
        ),
    ]
