# Generated by Django 4.2.8 on 2023-12-10 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientAPI', '0011_alter_order_datetimes_remove_order_goods_order_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetimes',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 13, 3, 47, 143036, tzinfo=datetime.timezone.utc), verbose_name='datetimes'),
        ),
    ]
