# Generated by Django 4.2.8 on 2023-12-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientAPI', '0012_alter_order_datetimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetimes',
            field=models.DateTimeField(default='Dec 10', verbose_name='datetimes'),
        ),
    ]
