# Generated by Django 4.2.8 on 2023-12-12 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientAPI', '0014_alter_order_datetimes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='orders_files/')),
            ],
            options={
                'db_table': 'Files',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='datetimes',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 16, 34, 47, 529804, tzinfo=datetime.timezone.utc), verbose_name='datetimes'),
        ),
    ]
