# Generated by Django 4.2.8 on 2023-12-12 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientAPI', '0019_alter_order_datetimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetimes',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 17, 29, 53, 317482, tzinfo=datetime.timezone.utc), verbose_name='datetimes'),
        ),
    ]
